// <auto-generated />
namespace ExerciseAssiatant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class a_mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a_mig));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051456111_a_mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
